FROM balena/open-balena-base:v13.0.1

WORKDIR /usr/src/jellyfish-test

# Download go-task (taskfile)
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

# Add repository for postgresql-client-12
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

# Install chrome dependencies and postgresql-client
RUN apt-get update && apt-get install -y libx11-xcb1 libxcomposite1 \
	libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 \
	gconf-gsettings-backend libasound2 libatk1.0-0 libgtk-3-0 libxshmfence1 \
	libxcb-dri3-0 libdrm-dev libgbm-dev postgresql-client-12 && rm -rf /var/lib/apt/lists/*

# So we can skip chromium downloads later
ENV PUPPETEER_EXECUTABLE_PATH=/usr/local/bin/chrome
COPY package*.json /usr/src/jellyfish-test/
RUN npm install && \
      /bin/bash -l -c 'ln -s $(find /usr/src/jellyfish-test/node_modules -type f -executable -name chrome) $PUPPETEER_EXECUTABLE_PATH'
