FROM balena/open-balena-base:v13.3.1

WORKDIR /usr/src/jellyfish-test

# Download go-task (taskfile)
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

# Add repository for postgresql-client-13
RUN apt-get update && \
	apt-get install -y lsb-release && \
	echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list; \
	apt-get purge lsb-release
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

# Install chromium dependencies and postgresql-client
RUN apt-get update && \
	apt-get install -y libx11-xcb1 libxcomposite1 libxcursor1 \
		libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 \
		gconf-gsettings-backend libasound2 libatk1.0-0 libgtk-3-0 \
		libxshmfence1 libxcb-dri3-0 libdrm-dev libgbm-dev \
		postgresql-client-13 && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

# So we can skip chromium downloads later
COPY package*.json /usr/src/jellyfish-test/
RUN npm install && npx playwright install chromium
